cmd/zrobot
docs/getting_started.md
zerorobot/cli/robot.py
zerorobot/cli/server.py
zerorobot/cli/service.py
zerorobot/cli/task.py
zerorobot/cli/template.py
zerorobot/cli/utils.py
zerorobot/dsl/ZeroRobotClient.py
zerorobot/service_proxy.py

improve zstor CLI to allow interaction with 0-robot from the terminal

---

zerorobot/cli/service.py

remove create command from zrobot service group

---

api_spec/api.html
api_spec/main.raml
docs/services/README.md
docs/templates/README.md
templates/zeroos_bootstrap/zeroos_bootstrap.py
templates/zerotier_client/zerotier_client.py
tests/fixtures/blueprints/bad_service_key.bp
tests/fixtures/blueprints/bad_service_name.bp
tests/fixtures/blueprints/bad_template_name.bp
tests/fixtures/blueprints/missing_actions.bp
tests/fixtures/blueprints/valid.bp
tests/test_service_template.py
tests/test_zrobot_client.py
zerorobot/blueprint.py
zerorobot/dsl/ZeroRobotAPI.py
zerorobot/dsl/ZeroRobotManager.py
zerorobot/server/apidocs/api.raml
zerorobot/server/handlers/createServiceHandler.py
zerorobot/server/handlers/schema/ServiceCreate_schema.json
zerorobot/server/types/ServiceCreate.py
zerorobot/service_collection.py
zerorobot/template/base.py
zerorobot/template_collection.py

allow to create service without a name

---

docs/quickstart.md

Quickstart for 0-robot on how to run the server, using the dsl, creating service and scheduling an action

quickstart with 0-robot

---

docs/services/README.md
tests/test_greenlets_mgr.py
tests/test_service_template.py
zerorobot/robot.py
zerorobot/service_collection.py
zerorobot/template/base.py

+ add documentation how to use gl manager and
an example code of a use case
closes #36

expose GreenletManager into TemplateBase

---

zerorobot/server/handlers/ExecuteBlueprintHandler.py

properly schedule action from blueprint

---

docs/services/README.md
tests/test_service_template.py
zerorobot/dsl/ZeroRobotManager.py
zerorobot/template/data.py

fix update_data flow

---

docs/quickstart.md

Update proposal for the quickstart guide
closes #57

Updates quickstart guide

---

zerorobot/cli/robot.py

zrobot CLI: make sure to use address passed in argument

---

tests/fixtures/blueprints/duplicate_name.bp
tests/test_blueprints.py
zerorobot/server/handlers/ExecuteBlueprintHandler.py

add test for actions exection from blueprint

---

docs/api/zerorobot/cli/robot.m.html
docs/api/zerorobot/dsl/ZeroRobotAPI.m.html
docs/api/zerorobot/server/handlers/ExecuteBlueprintHandler.m.html
docs/api/zerorobot/server/handlers/views.m.html
docs/api/zerorobot/service_collection.m.html
docs/api/zerorobot/service_proxy.m.html
docs/api/zerorobot/template/data.m.html
docs/api/zerorobot/template_collection.m.html
tests/test_service_collection.py
tests/test_service_template.py
tests/test_template_collection.py
tests/test_zrobot_api.py
zerorobot/dsl/ZeroRobotAPI.py
zerorobot/service_collection.py
zerorobot/template_collection.py

add get and exists method on ZeroRobotAPI class 

---

tests/test_template_collection.py
zerorobot/template_collection.py

add support for new git repo url pattern

---

Makefile
tests/server/test_services.py

- listServices
- listActions
part of: #7

add test for server API

---

zerorobot/cli/blueprint.py
zerorobot/cli/robot.py
zerorobot/cli/task.py

better error handling for CLI

---

zerorobot/robot.py
zerorobot/template/base.py

now that services can deduct were to store their data
by their own, we can schedule auto save directly
from the TemplateBase

move auto save into TemplateBase

---

requirements.txt
setup.py
tests/test_service_proxy.py
tests/test_tasklist.py
tests/test_zrobot_api.py
tests/test_zrobot_client.py
zerorobot/prometheus/flask/__init__.py
zerorobot/prometheus/host/__init__.py
zerorobot/prometheus/host/linux/__init__.py
zerorobot/prometheus/host/linux/cpu_stat.py
zerorobot/prometheus/host/linux/disk_stat.py
zerorobot/prometheus/host/linux/mem_stat.py
zerorobot/prometheus/host/linux/net_stat.py
zerorobot/prometheus/robot/__init__.py
zerorobot/robot.py
zerorobot/task.py
zerorobot/template/base.py

- setup prometheus /metrics endpoint

instrumentalization of 0-robot

---

tests/test_service_proxy.py
tests/test_tasklist.py
tests/test_zrobot_api.py
zerorobot/cli/robot.py
zerorobot/cli/utils.py
zerorobot/server/handlers/GetTaskHandler.py
zerorobot/service_collection.py
zerorobot/service_proxy.py
zerorobot/task/__init__.py
zerorobot/task/storage/__init__.py
zerorobot/task/storage/base.py
zerorobot/task/storage/file.py
zerorobot/task/storage/redis.py
zerorobot/task/task.py
zerorobot/task/task_list.py
zerorobot/task/utils.py
zerorobot/template/base.py

closes #19
- task that are done are now stored on the filesystem, so we
don't have to keep that in memory. that should release the memory
pressure of the 0-robot

implement TaskStorage interface on top of filesystem

---

Makefile
tests/fixtures/templates/node/node.py
tests/server/test_services.py
zerorobot/server/handlers/ListActionsHandler.py

properly handle property when listing action of a service

---

zerorobot/cli/server.py
zerorobot/robot.py

fix logger level setting

---

tests/fixtures/templates/node/node.py
tests/server/test_services.py
tests/test_service_template.py
zerorobot/template/base.py

support **kwargs in the action arguments

---

.travis.yml
tests/fixtures/templates/node/node.py
tests/server/test_services.py
tests/test_service_proxy.py
tests/test_task.py
zerorobot/server/handlers/views.py
zerorobot/task/storage/file.py
zerorobot/task/storage/redis.py
zerorobot/task/task.py
zerorobot/task/task_list.py
zerorobot/template/base.py

rename `eco.toJSON` to `eco.json`

---

docs/getting_started.md
tests/test_robot.py
zerorobot/cli/server.py
zerorobot/robot.py
zerorobot/template_collection.py

support specifying branch in template repo URL

---

utils/scripts/autobuild/node_startup.toml
utils/scripts/autobuild/startup.toml

Also use exec instead of just starting a sub process
> I couldn't test this because i have no mean to rebuild the flist. We need test it before merging of course

Move specific flist env to container startup

---

tests/fixtures/templates/node_updatedata/node_updatedata.py
tests/fixtures/templates/node_updatedata/schema.capnp
tests/test_service_template.py
zerorobot/template/base.py

make update_data a noop per default

---

JumpScale9Zrobot/clients/zerorobot/ZeroRobotClient.py
setup.py

Implement transparent JWT refresh mechanism

---

docs/quickstart.md

Related to https://docs.greenitglobe.com/gig/org_development/issues/21 story

Update quickstart: fix missed line in helloword.py

---

docs/getting_started.md

Relates to https://docs.greenitglobe.com/gig/org_development/issues/21 story

Fix installation procedure in getting started doc

---

tests/fixtures/templates_2/node/node.py
tests/fixtures/templates_2/node/schema.capnp
tests/test_template_collection.py
zerorobot/template_collection.py

add test for get template by name whith conflicting name

---

zerorobot/cli/server.py
zerorobot/robot/robot.py

add mode flag to allow auto install of the node template

---

zerorobot/robot/config_repo.py

fix config repo sshkey path search

---

JumpScale9Zrobot/clients/zerorobot/api_spec/main.raml
JumpScale9Zrobot/clients/zerorobot/client/Service.py
JumpScale9Zrobot/clients/zerorobot/client/ServiceCreate.py
JumpScale9Zrobot/clients/zerorobot/client/ServiceCreated.py
api_spec/api.html
api_spec/main.raml
tests/test_service_collection.py
tests/test_service_proxy.py
tests/test_zrobot_client.py
zerorobot/dsl/ZeroRobotAPI.py
zerorobot/dsl/ZeroRobotManager.py
zerorobot/server/apidocs/api.raml
zerorobot/server/auth/auth.py
zerorobot/server/handlers/__init__.py
zerorobot/server/handlers/createServiceHandler.py
zerorobot/server/handlers/listServicesHandler.py
zerorobot/server/handlers/schema/ServiceCreate_schema.json
zerorobot/server/handlers/schema/ServiceCreated_schema.json
zerorobot/server/handlers/schema/Service_schema.json
zerorobot/server/handlers/views.py
zerorobot/server/services_api.py
zerorobot/server/types/Service.py
zerorobot/server/types/ServiceCreate.py
zerorobot/server/types/ServiceCreated.py
zerorobot/service_collection.py
zerorobot/task/storage/sqlite.py
zerorobot/template/base.py

allow to create public services

---

tests/fixtures/templates/validate/schema.capnp
tests/fixtures/templates/validate/validate.py
tests/test_blueprints.py
tests/test_zrobot_client.py
zerorobot/server/handlers/ExecuteBlueprintHandler.py

cleanup service created in a blueprint if the blueprint fails

---

docs/services/actions.md
tests/fixtures/templates/cleanup/cleanup.py
tests/fixtures/templates/cleanup/schema.capnp
tests/test_service_template.py
tests/test_zrobot_client.py
zerorobot/task/task_list.py
zerorobot/task/utils.py
zerorobot/template/base.py

fixes #157
@FastGeert @grimpy please check if this would solve your problem.
Now that we have this in place, I can also provide a decorator so template developer can decorate the methods he wants and bind them to the delete action.
Only problem with the decorator is that I can't control the order to the callback.

add a way to bind an action to the delete method

---

docs/_sidebar.md

Enable github pages under docs

Created sidebar file
